Ci workflows update (#40)
* Update 'build' CI workflow.

* Update 'Security' CI workflow.

* Add 'semgrep' security scanner to 'Security' CI workflow.

diff --git a/.github/workflows/security.yml b/.github/workflows/security.yml
--- a/.github/workflows/security.yml
+++ b/.github/workflows/security.yml
@@ -9,18 +9,51 @@ on:
     - cron: '30 12 * * 3'
 
 jobs:
-  analyze:
-    name: Security check
+  gosec:
+    name: gosec check
     runs-on: ubuntu-latest
     env:
       GO111MODULE: on
     steps:
       - name: Checkout Source
         uses: actions/checkout@v3
-      - name: Run Gosec Security Scanner
+      - name: Run gosec security scanner
         uses: securego/gosec@v2.11.0
         with:
-          args: ./...
+          # with '-no-fail' we let the report trigger content trigger a failure using the GitHub Security features.
+          args: "-no-fail -fmt sarif -out gosec.sarif ./..."
+      - name: Upload SARIF file for GitHub Advanced Security Dashboard
+        uses: github/codeql-action/upload-sarif@v2
+        with:
+          sarif_file: gosec.sarif
+
+  semgrep:
+    name: semgrep scan
+    runs-on: ubuntu-latest
+    container:
+      image: returntocorp/semgrep
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+        # we let the report trigger content trigger a failure using the GitHub Security features.
+        # see https://semgrep.dev/docs/cli-usage/#exit-codes for more details.
+      - name: Run semgrep security scanner
+        run: |
+          cat << 'EOF' | bash
+              semgrep ci --config=auto --sarif --output=semgrep.sarif --max-target-bytes=2MB
+              EXIT_CODE=$?
+              if [ "$EXIT_CODE" = "0" ] || [ "$EXIT_CODE" = "1" ]
+              then
+                exit 0
+              else
+                exit $EXIT_CODE
+              fi
+          EOF
+      - name: Upload SARIF file for GitHub Advanced Security Dashboard
+        uses: github/codeql-action/upload-sarif@v2
+        with:
+          sarif_file: semgrep.sarif
+
   vuln-scan:
     name: Vulnerability scanner
     runs-on: ubuntu-latest
